projectVersion=6.0.0-SNAPSHOT
grailsVersion=6.2.3
javaVersion=17
asciidoctorGradlePluginVersion=4.0.4

grailsGradlePluginVersion=6.2.4
version=0.1

# This prevents the Grails Gradle Plugin from unnecessarily excluding slf4j-simple in the generated POMs
# https://github.com/grails/grails-gradle-plugin/issues/222
slf4jPreventExclusion=true

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
