plugins {
    id 'com.gradle.develocity' version '4.0.2'
    id 'com.gradle.common-custom-user-data-gradle-plugin' version '2.3'
}

def isCI = System.getenv().containsKey('CI')
def isLocal = !isCI

develocity {
    server = 'https://ge.grails.org'
    buildScan {
        tag('grails-plugins')
        tag('grails-cache-redis')
        publishing.onlyIf { it.authenticated }
        uploadInBackground = isLocal
    }
}

buildCache {
    local { enabled = isLocal }
    remote(develocity.buildCache) {
        enabled = true
        push = isCI
    }
}

rootProject.name = 'grails-cache-redis'
include 'functional-tests'