[versions]
grails-gradle-plugin = '6.2.4'
nexus-publish-gradle-plugin = '2.0.0'
asciidoctor-gradle-plugin = '4.0.4'

[libraries]
grails-gradle-plugin = { module = 'org.grails:grails-gradle-plugin', version.ref = 'grails-gradle-plugin' }
nexus-publish-gradle-plugin = { module = 'io.github.gradle-nexus:publish-plugin', version.ref = 'nexus-publish-gradle-plugin' }
asciidoctor-gradle-plugin = {module = 'org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin', version.ref = 'asciidoctor-gradle-plugin'}